package protobuf;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracer.proto

public final class Tracer {
  private Tracer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TraceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trace)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string source = 1;</code>
     */
    java.lang.String getSource();
    /**
     * <code>string source = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <code>string input = 2;</code>
     */
    java.lang.String getInput();
    /**
     * <code>string input = 2;</code>
     */
    com.google.protobuf.ByteString
        getInputBytes();

    /**
     * <code>int32 steps = 3;</code>
     */
    int getSteps();
  }
  /**
   * <pre>
   *Traces are the requests to be sent to tracers processes.
   *Traces must have a source to be executed and may have some input.
   *The steps field defines the maxium number of steps to inspect.
   * </pre>
   *
   * Protobuf type {@code Trace}
   */
  public  static final class Trace extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Trace)
      TraceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trace.newBuilder() to construct.
    private Trace(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trace() {
      source_ = "";
      input_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trace(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              input_ = s;
              break;
            }
            case 24: {

              steps_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Tracer.internal_static_Trace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Tracer.internal_static_Trace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Tracer.Trace.class, Tracer.Trace.Builder.class);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object source_;
    /**
     * <code>string source = 1;</code>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <code>string source = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 2;
    private volatile java.lang.Object input_;
    /**
     * <code>string input = 2;</code>
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        input_ = s;
        return s;
      }
    }
    /**
     * <code>string input = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STEPS_FIELD_NUMBER = 3;
    private int steps_;
    /**
     * <code>int32 steps = 3;</code>
     */
    public int getSteps() {
      return steps_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, source_);
      }
      if (!getInputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, input_);
      }
      if (steps_ != 0) {
        output.writeInt32(3, steps_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, source_);
      }
      if (!getInputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, input_);
      }
      if (steps_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, steps_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Tracer.Trace)) {
        return super.equals(obj);
      }
      Tracer.Trace other = (Tracer.Trace) obj;

      if (!getSource()
          .equals(other.getSource())) return false;
      if (!getInput()
          .equals(other.getInput())) return false;
      if (getSteps()
          != other.getSteps()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
      hash = (37 * hash) + STEPS_FIELD_NUMBER;
      hash = (53 * hash) + getSteps();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Tracer.Trace parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tracer.Trace parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tracer.Trace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tracer.Trace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tracer.Trace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tracer.Trace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tracer.Trace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tracer.Trace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tracer.Trace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Tracer.Trace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tracer.Trace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tracer.Trace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Tracer.Trace prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Traces are the requests to be sent to tracers processes.
     *Traces must have a source to be executed and may have some input.
     *The steps field defines the maxium number of steps to inspect.
     * </pre>
     *
     * Protobuf type {@code Trace}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trace)
        Tracer.TraceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Tracer.internal_static_Trace_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Tracer.internal_static_Trace_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Tracer.Trace.class, Tracer.Trace.Builder.class);
      }

      // Construct using Tracer.Trace.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        source_ = "";

        input_ = "";

        steps_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Tracer.internal_static_Trace_descriptor;
      }

      @java.lang.Override
      public Tracer.Trace getDefaultInstanceForType() {
        return Tracer.Trace.getDefaultInstance();
      }

      @java.lang.Override
      public Tracer.Trace build() {
        Tracer.Trace result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Tracer.Trace buildPartial() {
        Tracer.Trace result = new Tracer.Trace(this);
        result.source_ = source_;
        result.input_ = input_;
        result.steps_ = steps_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Tracer.Trace) {
          return mergeFrom((Tracer.Trace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Tracer.Trace other) {
        if (other == Tracer.Trace.getDefaultInstance()) return this;
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (!other.getInput().isEmpty()) {
          input_ = other.input_;
          onChanged();
        }
        if (other.getSteps() != 0) {
          setSteps(other.getSteps());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Tracer.Trace parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Tracer.Trace) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object source_ = "";
      /**
       * <code>string source = 1;</code>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string source = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string source = 1;</code>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string source = 1;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <code>string source = 1;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object input_ = "";
      /**
       * <code>string input = 2;</code>
       */
      public java.lang.String getInput() {
        java.lang.Object ref = input_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          input_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string input = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        java.lang.Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string input = 2;</code>
       */
      public Builder setInput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string input = 2;</code>
       */
      public Builder clearInput() {
        
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>string input = 2;</code>
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        input_ = value;
        onChanged();
        return this;
      }

      private int steps_ ;
      /**
       * <code>int32 steps = 3;</code>
       */
      public int getSteps() {
        return steps_;
      }
      /**
       * <code>int32 steps = 3;</code>
       */
      public Builder setSteps(int value) {
        
        steps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 steps = 3;</code>
       */
      public Builder clearSteps() {
        
        steps_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Trace)
    }

    // @@protoc_insertion_point(class_scope:Trace)
    private static final Tracer.Trace DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Tracer.Trace();
    }

    public static Tracer.Trace getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trace>
        PARSER = new com.google.protobuf.AbstractParser<Trace>() {
      @java.lang.Override
      public Trace parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trace(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trace> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trace> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Tracer.Trace getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Result)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Step steps = 1;</code>
     */
    java.util.List<SnapshotOuterClass.Step> 
        getStepsList();
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    SnapshotOuterClass.Step getSteps(int index);
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    int getStepsCount();
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    java.util.List<? extends SnapshotOuterClass.StepOrBuilder> 
        getStepsOrBuilderList();
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    SnapshotOuterClass.StepOrBuilder getStepsOrBuilder(
        int index);
  }
  /**
   * <pre>
   *Results store a list of all steps of a program.
   * </pre>
   *
   * Protobuf type {@code Result}
   */
  public  static final class Result extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Result)
      ResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Result.newBuilder() to construct.
    private Result(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Result() {
      steps_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Result(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                steps_ = new java.util.ArrayList<SnapshotOuterClass.Step>();
                mutable_bitField0_ |= 0x00000001;
              }
              steps_.add(
                  input.readMessage(SnapshotOuterClass.Step.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          steps_ = java.util.Collections.unmodifiableList(steps_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Tracer.internal_static_Result_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Tracer.internal_static_Result_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Tracer.Result.class, Tracer.Result.Builder.class);
    }

    public static final int STEPS_FIELD_NUMBER = 1;
    private java.util.List<SnapshotOuterClass.Step> steps_;
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    public java.util.List<SnapshotOuterClass.Step> getStepsList() {
      return steps_;
    }
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    public java.util.List<? extends SnapshotOuterClass.StepOrBuilder> 
        getStepsOrBuilderList() {
      return steps_;
    }
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    public int getStepsCount() {
      return steps_.size();
    }
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    public SnapshotOuterClass.Step getSteps(int index) {
      return steps_.get(index);
    }
    /**
     * <code>repeated .Step steps = 1;</code>
     */
    public SnapshotOuterClass.StepOrBuilder getStepsOrBuilder(
        int index) {
      return steps_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < steps_.size(); i++) {
        output.writeMessage(1, steps_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < steps_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, steps_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Tracer.Result)) {
        return super.equals(obj);
      }
      Tracer.Result other = (Tracer.Result) obj;

      if (!getStepsList()
          .equals(other.getStepsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStepsCount() > 0) {
        hash = (37 * hash) + STEPS_FIELD_NUMBER;
        hash = (53 * hash) + getStepsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Tracer.Result parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tracer.Result parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tracer.Result parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tracer.Result parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tracer.Result parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Tracer.Result parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Tracer.Result parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tracer.Result parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tracer.Result parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Tracer.Result parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Tracer.Result parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Tracer.Result parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Tracer.Result prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *Results store a list of all steps of a program.
     * </pre>
     *
     * Protobuf type {@code Result}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Result)
        Tracer.ResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Tracer.internal_static_Result_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Tracer.internal_static_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Tracer.Result.class, Tracer.Result.Builder.class);
      }

      // Construct using Tracer.Result.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStepsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (stepsBuilder_ == null) {
          steps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          stepsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Tracer.internal_static_Result_descriptor;
      }

      @java.lang.Override
      public Tracer.Result getDefaultInstanceForType() {
        return Tracer.Result.getDefaultInstance();
      }

      @java.lang.Override
      public Tracer.Result build() {
        Tracer.Result result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Tracer.Result buildPartial() {
        Tracer.Result result = new Tracer.Result(this);
        int from_bitField0_ = bitField0_;
        if (stepsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            steps_ = java.util.Collections.unmodifiableList(steps_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.steps_ = steps_;
        } else {
          result.steps_ = stepsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Tracer.Result) {
          return mergeFrom((Tracer.Result)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Tracer.Result other) {
        if (other == Tracer.Result.getDefaultInstance()) return this;
        if (stepsBuilder_ == null) {
          if (!other.steps_.isEmpty()) {
            if (steps_.isEmpty()) {
              steps_ = other.steps_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStepsIsMutable();
              steps_.addAll(other.steps_);
            }
            onChanged();
          }
        } else {
          if (!other.steps_.isEmpty()) {
            if (stepsBuilder_.isEmpty()) {
              stepsBuilder_.dispose();
              stepsBuilder_ = null;
              steps_ = other.steps_;
              bitField0_ = (bitField0_ & ~0x00000001);
              stepsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStepsFieldBuilder() : null;
            } else {
              stepsBuilder_.addAllMessages(other.steps_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Tracer.Result parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Tracer.Result) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<SnapshotOuterClass.Step> steps_ =
        java.util.Collections.emptyList();
      private void ensureStepsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          steps_ = new java.util.ArrayList<SnapshotOuterClass.Step>(steps_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          SnapshotOuterClass.Step, SnapshotOuterClass.Step.Builder, SnapshotOuterClass.StepOrBuilder> stepsBuilder_;

      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public java.util.List<SnapshotOuterClass.Step> getStepsList() {
        if (stepsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(steps_);
        } else {
          return stepsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public int getStepsCount() {
        if (stepsBuilder_ == null) {
          return steps_.size();
        } else {
          return stepsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public SnapshotOuterClass.Step getSteps(int index) {
        if (stepsBuilder_ == null) {
          return steps_.get(index);
        } else {
          return stepsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder setSteps(
          int index, SnapshotOuterClass.Step value) {
        if (stepsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepsIsMutable();
          steps_.set(index, value);
          onChanged();
        } else {
          stepsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder setSteps(
          int index, SnapshotOuterClass.Step.Builder builderForValue) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.set(index, builderForValue.build());
          onChanged();
        } else {
          stepsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder addSteps(SnapshotOuterClass.Step value) {
        if (stepsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepsIsMutable();
          steps_.add(value);
          onChanged();
        } else {
          stepsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder addSteps(
          int index, SnapshotOuterClass.Step value) {
        if (stepsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStepsIsMutable();
          steps_.add(index, value);
          onChanged();
        } else {
          stepsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder addSteps(
          SnapshotOuterClass.Step.Builder builderForValue) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.add(builderForValue.build());
          onChanged();
        } else {
          stepsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder addSteps(
          int index, SnapshotOuterClass.Step.Builder builderForValue) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.add(index, builderForValue.build());
          onChanged();
        } else {
          stepsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder addAllSteps(
          java.lang.Iterable<? extends SnapshotOuterClass.Step> values) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, steps_);
          onChanged();
        } else {
          stepsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder clearSteps() {
        if (stepsBuilder_ == null) {
          steps_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          stepsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public Builder removeSteps(int index) {
        if (stepsBuilder_ == null) {
          ensureStepsIsMutable();
          steps_.remove(index);
          onChanged();
        } else {
          stepsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public SnapshotOuterClass.Step.Builder getStepsBuilder(
          int index) {
        return getStepsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public SnapshotOuterClass.StepOrBuilder getStepsOrBuilder(
          int index) {
        if (stepsBuilder_ == null) {
          return steps_.get(index);  } else {
          return stepsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public java.util.List<? extends SnapshotOuterClass.StepOrBuilder> 
           getStepsOrBuilderList() {
        if (stepsBuilder_ != null) {
          return stepsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(steps_);
        }
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public SnapshotOuterClass.Step.Builder addStepsBuilder() {
        return getStepsFieldBuilder().addBuilder(
            SnapshotOuterClass.Step.getDefaultInstance());
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public SnapshotOuterClass.Step.Builder addStepsBuilder(
          int index) {
        return getStepsFieldBuilder().addBuilder(
            index, SnapshotOuterClass.Step.getDefaultInstance());
      }
      /**
       * <code>repeated .Step steps = 1;</code>
       */
      public java.util.List<SnapshotOuterClass.Step.Builder> 
           getStepsBuilderList() {
        return getStepsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          SnapshotOuterClass.Step, SnapshotOuterClass.Step.Builder, SnapshotOuterClass.StepOrBuilder> 
          getStepsFieldBuilder() {
        if (stepsBuilder_ == null) {
          stepsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              SnapshotOuterClass.Step, SnapshotOuterClass.Step.Builder, SnapshotOuterClass.StepOrBuilder>(
                  steps_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          steps_ = null;
        }
        return stepsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Result)
    }

    // @@protoc_insertion_point(class_scope:Result)
    private static final Tracer.Result DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Tracer.Result();
    }

    public static Tracer.Result getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Result>
        PARSER = new com.google.protobuf.AbstractParser<Result>() {
      @java.lang.Override
      public Result parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Result(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Result> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Result> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Tracer.Result getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trace_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trace_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Result_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014tracer.proto\032\016snapshot.proto\"5\n\005Trace\022" +
      "\016\n\006source\030\001 \001(\t\022\r\n\005input\030\002 \001(\t\022\r\n\005steps\030" +
      "\003 \001(\005\"\036\n\006Result\022\024\n\005steps\030\001 \003(\0132\005.Stepb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          SnapshotOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trace_descriptor,
        new java.lang.String[] { "Source", "Input", "Steps", });
    internal_static_Result_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Result_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Result_descriptor,
        new java.lang.String[] { "Steps", });
    SnapshotOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
