@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@contentType = application/json

###
GET http://{{host}}/api/tracer/languages

### Fail ###
###
POST http://{{host}}/api/tracer/trace

###
POST http://{{host}}/api/tracer/trace

{
    "language": "python"
}

###
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "qwerty"
}


### Java ###


### Python ###

### 
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": ""
}

### 
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": "print('hello world!')"
}

### 
POST http://{{host}}/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": "print(input('type the input\n'))"
}

###
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": "print(input('type the input\\n'))",
    "input": "some random input"
}

### 
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": "while True:\n    pass"
}

### 
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": "while True: pass"
}

### 
POST http://{{host}}/api/tracer/trace
Content-Type: {{contentType}}

{
    "language": "python",
    "source": "import time\ntime.sleep(10)"
}
